## This workflow aims to run the end-to-end tests in canary fashion to
## test the prod artifacts for APM enablement.
name: APM Enablement E2E main-build testing
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}

permissions:
  id-token: write
  contents: read

env:
  APM_REGISTRY: 160148376629.dkr.ecr.us-west-2.amazonaws.com
  APM_PREVIEW_REPO: aws-apm-preview

jobs:
  e2e-canary-test:
    uses: ./.github/workflows/apm-e2e-test.yml
    secrets: inherit
    with:
      test-cluster-name: 'pulse-playground'
      caller-workflow-name: 'apm-e2e-main-build-test'
