# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: APM Release
on:
  push:
  workflow_dispatch:
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: ./apm-e2e-test.yml
        with:
          test-cluster-name: 'pulse-cw-agent-operator-test'
          apm-cwagent-operator-image-name: ${{ secrets.TEST }}