# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: APM Release
on:
  push:
  workflow_dispatch:
jobs:
  testrun:
    uses: actions/checkout@v3
    with:
      fetch-depth: 0

